language: cpp

stages: deploy
jobs:
  include:
    - stage: deploy
      name: "gcc"
      os: linux
      compiler: gcc
      env: COMPILER=gcc
      script: 
        - deploy-docker.sh;
    - name: "clang"
      os: linux
      compiler: clang
      env: COMPILER=clang
      script: 
        - deploy-docker.sh;