language: cpp

stages: deploy
jobs:
  include:
    - stage: deploy
      name: "gcc"
      os: linux
      compiler: gcc
      script: 
        - ./deploy-docker.sh;
    - name: "clang"
      os: linux
      compiler: clang
      script: 
        - ./deploy-docker.sh;